# Site settings
title: Wawer.IT
email: krzysztof@wawer.it
description: > # this means to ignore newlines until "baseurl:"
  Helping with cleaning up legacy code and improving development process.
domain: blog.wawer.it
url: "https://blog.wawer.it" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
twitter_username: chris_wawer
github_username:  wafcio

# Build settings
markdown: kramdown

google_analytics: G-B2KG3ZHSZY

paginate: 3
paginate_path: "page:num"

date_locale: en

plugins:
  - jekyll-archives

jekyll-archives:
  enabled:
    - month
    - categories
  layouts:
    month: archive/month
    category: archive/category
